### ISSUE TITLE
Change Default Lunar JRE Path.

### ISSUE THREAD

**Issue by Aetopia** [couleur-tweak-tips/Moony#1]
Currently the Path is set too:
`$env:USERPROFILE\.lunarclient\jre\zulu*-jre*-win_x*\bin\javaw.exe`
change it too:
`$env:USERPROFILE\.lunarclient\jre\$ver\zulu*-jre*-win_x*\bin\javaw.exe`

**Comment by couleurm** [comment]
ru sure
![image](https://user-images.githubusercontent.com/82747632/148687121-773eea68-265a-4b8b-8caa-41907135c3a0.png)

**Comment by Aetopia** [comment]
The PowerShell script will be looking for `$env:USERPROFILE\.lunarclient\jre\zulu*-jre*-win_x*\bin\javaw.exe` instead of the version specific JRE. Resulting in the Script to fallback to additional JREs instead of using the default one.

**Comment by couleurm** [comment]
Should be fine now
