### ISSUE TITLE
moony not detecting my custom .minecraft directory

### ISSUE THREAD

**Issue by painelle** [couleur-tweak-tips/Moony#7]
the thing i typed to change directory
![image](https://user-images.githubusercontent.com/71561421/183817798-62019f59-2819-4a7a-942c-80113580495b.png)

this is the .minecraft im trying to make moony go on
E:\Minecraft\LabyMod 1.8.9 (Forge)

but instead its making a new .minecraft named
E:\Minecraft\LabyMod
![image](https://user-images.githubusercontent.com/71561421/183818016-b9858c3e-59c6-44b3-9311-1d7ee272e0dc.png)

im fairly certain its because of the spaces

**Comment by couleurm** [comment]
Moony was not designed for LabyMod, and is currently not compatible with the way LC's files are organized in the new update

**Comment by painelle** [comment]
its not labymod
its a long story but the short story is lunar has launching problems with my normal .minecraft so i used my other .minecraft (which is my labymod .minecraft) and now it works.

**Comment by painelle** [comment]
also please try it out for urself,

make a new .minecraft anywhere but have a space somewhere in the file name and try to launch moony with the same .minecraft that was just created it will make a new folder instead of using the one just made

**Comment by couleurm** [comment]
> and is currently not compatible with the way LC's files are organized in the new update
